### ISSUE TITLE
Regarding data accessibility 

### ISSUE THREAD

**Issue by AritraBanik08** [ire4ever1190/mike#31]
I have another question [here](https://gitlab.com/a60030/ab/) I have used redis to send data from one link to another. Is there a better way to do this in mike? If yes, can you show it to me.

**Comment by ire4ever1190** [comment]
I see you removed in the redis in [#c7419625](https://gitlab.com/a60030/ab/-/commit/c74196251a2a7090b747aee830096d9666b0be4d), the new cookie solution looks pretty good.

Another way of doing it is that when a user creates a reservation it gets saved to the database and they get returned a reservation ID. Then later they can make a request to `/reservations/:id` and the server just looks up check-in/check-out times from the DB

**Comment by AritraBanik08** [comment]
Can you tell me why the session cookie is not working on the line 240 and 241 [here](https://gitea.com/cereci5049/Shoppers). It's working sometimes and not working other times now the session cookies are working only on chrome and not in firefox and safari.
