### ISSUE TITLE
Issue while using `ctx.queryParams`

### ISSUE THREAD

**Issue by boat12022** [ire4ever1190/mike#32]
Please can you help me with the code here at this link https://gitea.com/cereci5049/Shoppers/src/branch/main/src/a3.nim. In `"/checkout" -> post:` the `ctx.queryParams["prod"]` is not working. Can you help me with that. Thank you.

**Comment by ire4ever1190** [comment]
This works locally
```nim
import mike

"/test" -> post:
  ctx.redirect("/checkout?prod=test")

"/checkout" -> post:
  echo ctx.queryParams["prod"]

run()
```
Are you running into a certain error? Like is an exception occuring?

Also not related to the issue but you can use [getOrDefault](https://nim-lang.org/docs/strtabs.html#getOrDefault%2CStringTableRef%2Cstring%2Cstring) instead of using a try/catch

**Comment by boat12022** [comment]
@ire4ever1190 no it is not showing any error but `ctx.queryParams` doesn't seem to be working properly in `"/checkout" -> post:`. It is working on other post requests, it is just not woring in this one.

**Comment by AritraBanik08** [comment]
Why not store the value in a hidden field in the nimja template and access it through `ctx.urlForm`.

**Comment by boat12022** [comment]
@ire4ever1190 I am facing another issue here. When i am redirecting from the login page to the `/checkout` route it is going to the `"/checkout" -> post` function. Can you please help me fix it. Thank you.

**Comment by ire4ever1190** [comment]
> @ire4ever1190 I am facing another issue here. When i am redirecting from the login page to the `/checkout` route it is going to the `"/checkout" -> post` function. Can you please help me fix it. Thank you.

Sorry been busy with work. Is the issue still around or is it closed alongside this?

**Comment by boat12022** [comment]
@ire4ever1190 No the error has been solved with the help of @AritraBanik08 and thanks for making such a great nim framework. Keep up the good work. Thank you for your time.
